version: 2
jobs:
  build:
    working_directory: /home/circleci/angular2-tslint-rules

    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package-lock.json" }}
            - deps-
      - run: npm install
      - save_cache:
          key: npm-dependencies-{{ checksum "package-lock.json" }}
          paths: 'node_modules'
      - run:
          name: Deploy
          command: /home/circleci/angular2-tslint-rules/deploy.sh $CIRCLE_BRANCH $NPM_TOKEN
